# Main Window
TITLE = "OpenGS - Map Tool"
VERSION = "0.2"

# Territory and Province Sizes
PIXELS_PER_LAND_TERRITORY_DEFAULT = 6000
PIXELS_PER_LAND_TERRITORY_MIN = PIXELS_PER_LAND_TERRITORY_DEFAULT // 3
PIXELS_PER_LAND_TERRITORY_MAX = PIXELS_PER_LAND_TERRITORY_DEFAULT * 3
PIXELS_PER_LAND_TERRITORY_TICK = (PIXELS_PER_LAND_TERRITORY_MAX - PIXELS_PER_LAND_TERRITORY_MIN) // 100
PIXELS_PER_LAND_TERRITORY_STEP = PIXELS_PER_LAND_TERRITORY_TICK // 2

PIXELS_PER_WATER_TERRITORY_DEFAULT = 35000
PIXELS_PER_WATER_TERRITORY_MIN = PIXELS_PER_WATER_TERRITORY_DEFAULT // 3
PIXELS_PER_WATER_TERRITORY_MAX = PIXELS_PER_WATER_TERRITORY_DEFAULT * 3
PIXELS_PER_WATER_TERRITORY_TICK = (PIXELS_PER_WATER_TERRITORY_MAX - PIXELS_PER_WATER_TERRITORY_MIN) // 100
PIXELS_PER_WATER_TERRITORY_STEP = PIXELS_PER_WATER_TERRITORY_TICK // 2

PIXELS_PER_LAND_PROVINCE_DEFAULT = 1200 # 1/5th
PIXELS_PER_LAND_PROVINCE_MIN = PIXELS_PER_LAND_PROVINCE_DEFAULT // 3
PIXELS_PER_LAND_PROVINCE_MAX = PIXELS_PER_LAND_PROVINCE_DEFAULT * 3
PIXELS_PER_LAND_PROVINCE_TICK = (PIXELS_PER_LAND_PROVINCE_MAX - PIXELS_PER_LAND_PROVINCE_MIN) // 100
PIXELS_PER_LAND_PROVINCE_STEP = PIXELS_PER_LAND_PROVINCE_TICK // 2

PIXELS_PER_WATER_PROVINCE_DEFAULT = 7000 # 1/5th
PIXELS_PER_WATER_PROVINCE_MIN = PIXELS_PER_WATER_PROVINCE_DEFAULT // 3
PIXELS_PER_WATER_PROVINCE_MAX = PIXELS_PER_WATER_PROVINCE_DEFAULT * 3
PIXELS_PER_WATER_PROVINCE_TICK = (PIXELS_PER_WATER_PROVINCE_MAX - PIXELS_PER_WATER_PROVINCE_MIN) // 100
PIXELS_PER_WATER_PROVINCE_STEP = PIXELS_PER_WATER_PROVINCE_TICK // 2

# Other Map Tool Arguments
LLOYD_ALGO_ITERATIONS_DEFAULT = 2
LLOYD_ALGO_ITERATIONS_MIN = 1
LLOYD_ALGO_ITERATIONS_MAX = 10
LLOYD_ALGO_ITERATIONS_TICK = 1
LLOYD_ALGO_ITERATIONS_STEP = 1

# Land Map Color Code
OCEAN_COLOR = (5, 20, 18)  # RGB
LAND_COLOR = (150, 68, 192)  # RGB
LAKE_COLOR = (0, 255, 0)  # RGB

# Boundary Map Color Code
BOUNDARY_COLOR = (0, 0, 0)

# Image Display
MAX_IMAGE_PIXELS = 300000000
DISPLAY_SIZE_WIDTH = 1050 // 2
DISPLAY_SIZE_HEIGHT = 900 // 2

# Number Series
AREA_ID_PREFIX = "area-"
TERRITORY_ID_PREFIX = "ter-"
PROVINCE_ID_PREFIX = "prv-"
SERIES_ID_START = 1
SERIES_ID_END = 999999

# RNG
CONT_AREAS_RNG_SEED = int(1e6)
TERRITORIES_RNG_SEED = int(2e6)
PROVINCES_RNG_SEED = int(3e6)
