# Main Window
TITLE = "OpenGS - Map Tool"
VERSION = "0.2.5"
SHOW_DENS_SAMPS = False

# Territory and Province Sizes
PIXELS_PER_LAND_DENS_SAMP_DEFAULT = 30_000  # 5x territory
PIXELS_PER_LAND_DENS_SAMP_MIN = PIXELS_PER_LAND_DENS_SAMP_DEFAULT // 3
PIXELS_PER_LAND_DENS_SAMP_MAX = PIXELS_PER_LAND_DENS_SAMP_DEFAULT * 3
PIXELS_PER_LAND_DENS_SAMP_TICK = (PIXELS_PER_LAND_DENS_SAMP_MAX - PIXELS_PER_LAND_DENS_SAMP_MIN) // 100
PIXELS_PER_LAND_DENS_SAMP_STEP = PIXELS_PER_LAND_DENS_SAMP_TICK // 2

PIXELS_PER_WATER_DENS_SAMP_DEFAULT = 175_000  # 5x territory
PIXELS_PER_WATER_DENS_SAMP_MIN = PIXELS_PER_WATER_DENS_SAMP_DEFAULT // 3
PIXELS_PER_WATER_DENS_SAMP_MAX = PIXELS_PER_WATER_DENS_SAMP_DEFAULT * 3
PIXELS_PER_WATER_DENS_SAMP_TICK = (PIXELS_PER_WATER_DENS_SAMP_MAX - PIXELS_PER_WATER_DENS_SAMP_MIN) // 100
PIXELS_PER_WATER_DENS_SAMP_STEP = PIXELS_PER_WATER_DENS_SAMP_TICK // 2

PIXELS_PER_LAND_TERRITORY_DEFAULT = 6_000
PIXELS_PER_LAND_TERRITORY_MIN = PIXELS_PER_LAND_TERRITORY_DEFAULT // 3
PIXELS_PER_LAND_TERRITORY_MAX = PIXELS_PER_LAND_TERRITORY_DEFAULT * 3
PIXELS_PER_LAND_TERRITORY_TICK = (PIXELS_PER_LAND_TERRITORY_MAX - PIXELS_PER_LAND_TERRITORY_MIN) // 100
PIXELS_PER_LAND_TERRITORY_STEP = PIXELS_PER_LAND_TERRITORY_TICK // 2

PIXELS_PER_WATER_TERRITORY_DEFAULT = 35_000
PIXELS_PER_WATER_TERRITORY_MIN = PIXELS_PER_WATER_TERRITORY_DEFAULT // 3
PIXELS_PER_WATER_TERRITORY_MAX = PIXELS_PER_WATER_TERRITORY_DEFAULT * 3
PIXELS_PER_WATER_TERRITORY_TICK = (PIXELS_PER_WATER_TERRITORY_MAX - PIXELS_PER_WATER_TERRITORY_MIN) // 100
PIXELS_PER_WATER_TERRITORY_STEP = PIXELS_PER_WATER_TERRITORY_TICK // 2

PIXELS_PER_LAND_PROVINCE_DEFAULT = 1_200 # 1/5th
PIXELS_PER_LAND_PROVINCE_MIN = PIXELS_PER_LAND_PROVINCE_DEFAULT // 3
PIXELS_PER_LAND_PROVINCE_MAX = PIXELS_PER_LAND_PROVINCE_DEFAULT * 3
PIXELS_PER_LAND_PROVINCE_TICK = (PIXELS_PER_LAND_PROVINCE_MAX - PIXELS_PER_LAND_PROVINCE_MIN) // 100
PIXELS_PER_LAND_PROVINCE_STEP = PIXELS_PER_LAND_PROVINCE_TICK // 2

PIXELS_PER_WATER_PROVINCE_DEFAULT = 7_000 # 1/5th
PIXELS_PER_WATER_PROVINCE_MIN = PIXELS_PER_WATER_PROVINCE_DEFAULT // 3
PIXELS_PER_WATER_PROVINCE_MAX = PIXELS_PER_WATER_PROVINCE_DEFAULT * 3
PIXELS_PER_WATER_PROVINCE_TICK = (PIXELS_PER_WATER_PROVINCE_MAX - PIXELS_PER_WATER_PROVINCE_MIN) // 100
PIXELS_PER_WATER_PROVINCE_STEP = PIXELS_PER_WATER_PROVINCE_TICK // 2


# Minimum and maximum density multiplier for region density calculation
DENSITY_MULTIPLIER_MIN = 0.25
DENSITY_MULTIPLIER_NORMAL = 1.0
DENSITY_MULTIPLIER_MAX = 4.0
# Syncronize with README and UI Instructions

# Other Map Tool Arguments
LLOYD_ALGO_ITERATIONS_DEFAULT = 2
LLOYD_ALGO_ITERATIONS_MIN = 1
LLOYD_ALGO_ITERATIONS_MAX = 10
LLOYD_ALGO_ITERATIONS_TICK = 1
LLOYD_ALGO_ITERATIONS_STEP = 1

MIN_AREA_PIXELS = 50

# Land Map Color Code
OCEAN_COLOR = (5, 20, 18)  # RGB
LAND_COLOR = (150, 68, 192)  # RGB
LAKE_COLOR = (0, 255, 0)  # RGB

# Image Import
MAX_IMAGE_PIXELS = 300_000_000

# Image Export (file extension is added later)
BOUNDARY_IMAGE_FILENAME = "Boundary Image"
FINAL_BOUNDARY_IMAGE_FILENAME = "Final Boundary && Density Image" # "&&"" results in one "&" in Qt UI
CLASS_IMAGE_FILENAME = "Classification Image"
CONTINUOUS_AREA_IMAGE_FILENAME = "Continuous Area Image"
DENS_SAMP_IMAGE_FILENAME = "Density Samples Image"
TERRITORY_IMAGE_FILENAME = "Territory Image"
PROVINCE_IMAGE_FILENAME = "Province Image"


# Number Series
AREA_ID_PREFIX = "AREA"
DENS_SAMP_ID_PREFIX = "DST"
TERRITORY_ID_PREFIX = "TRT"
PROVINCE_ID_PREFIX = "PRV"
SERIES_ID_START = 1
SERIES_ID_END = 999_999

